name: cli_dialog
description: Create beautiful and powerful CLI prompts in Inquirer.js style and test them.
version: 0.3.0
homepage: https://github.com/leonardoInf/cli_dialog

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  test: ^1.14.2
  pedantic: ^1.9.0
  example:
    path: ./example
