name: cli_dialog
description: Create beautiful and powerful CLI prompts in Inquirer.js style and test them.
version: 0.3.3
homepage: https://github.com/leonardoInf/cli_dialog

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  dart_console: ^0.6.2

dev_dependencies:
  test_coverage: ^0.4.3
  coveralls: ^5.2.0
  test: ^1.14.2
  pedantic: ^1.9.0
  example:
    path: ./example
