name: cli_dialog
description: Create beautiful and powerful CLI prompts in Inquirer.js style and test them.
version: 0.5.1
homepage: https://github.com/leonardoInf/cli_dialog
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dart_console:
    git:
      url: git@github.com:fabio21/dart_console.git

dev_dependencies:
  test_coverage: ^0.5.0
  coveralls: ^5.2.0
  test: ^1.16.5
  pedantic: ^1.11.0
  example:
    path: ./example
