name: cli_dialog
description: Create CLI dialogs in Angular CLI style
version: 0.0.1
homepage: https://github.com/leonardoInf/cli_dialog

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  test: ^1.14.2
  example:
    path: ./example
